name: wehere_client
description: wehere app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.16
  flutter_native_splash: ^2.2.17
  equatable: ^2.0.5
  dio: ^4.0.6
  provider: ^6.0.5
  get_it: ^7.2.0
  logger: ^1.1.0
  jwt_decode: ^0.3.1
  google_sign_in: ^5.4.3
  google_maps_flutter: ^2.2.3
  geolocator: ^9.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - asset/image/