name: wehere_client
description: wehere app

publish_to: 'none'

version: 1.0.5+6

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.16
  flutter_native_splash: ^2.2.17
  equatable: ^2.0.5
  dio: ^4.0.6
  provider: ^6.0.5
  get_it: ^7.2.0
  logger: ^1.1.0
  jwt_decode: ^0.3.1
  google_sign_in: ^5.4.3
  google_maps_flutter: ^2.2.3
  custom_info_window: ^1.0.1
  geolocator: ^9.0.2
  convex_bottom_bar: ^3.1.0+1
  image: ^4.0.13
  image_picker: ^0.8.6+1
  cached_network_image: ^3.2.3
  photo_view: ^0.14.0
  sign_in_with_apple: ^4.3.0
  flutter_screenutil: ^5.6.1
  google_maps_cluster_manager: ^3.0.0+1
  new_version: ^0.3.1
  flutter_datetime_picker: ^1.5.1
  intl: ^0.18.0
  fluttertoast: ^8.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - asset/image/

fonts:
  - family: Pretendard
    fonts:
      - asset: asset/font/Pretendard-Thin.otf
        weight: 100
      - asset: asset/font/Pretendard-ExtraLight.otf
        weight: 200
      - asset: asset/font/Pretendard-Light.otf
        weight: 300
      - asset: asset/font/Pretendard-Regular.otf
        weight: 400
      - asset: asset/font/Pretendard-Medium.otf
        weight: 500
      - asset: asset/font/Pretendard-SemiBold.otf
        weight: 600
      - asset: asset/font/Pretendard-Bold.otf
        weight: 700
      - asset: asset/font/Pretendard-ExtraBold.otf
        weight: 800
      - asset: asset/font/Pretendard-Black.otf
        weight: 900